name: psi-score

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get PSI Score
      id: psi
      uses: stefafafan/psi-action@v1.0.1
      with:
        url: 'https://nicole-how.github.io/'
        key: ${{ secrets.API_KEY_PAGE_SPEEDS }}
        strategy: 'mobile'

    - name: Echo score
      run: |
        echo "Score: ${{ steps.psi.outputs.score }} / 100"
        echo "FCP: ${{ steps.psi.outputs.first-contentful-paint }}"
        echo "FID: ${{ steps.psi.outputs.first-input-delay }}"
        echo "CLS: ${{ steps.psi.outputs.cumulative-layout-shift }}"
        echo "LCP: ${{ steps.psi.outputs.largest-contentful-paint }}"
        echo "Speed: ${{ steps.psi.outputs.speed-index }} / 100"
        echo "TOT: ${{ steps.psi.outputs.time-to-interactive }} / 100"
        echo "TBT: ${{ steps.psi.outputs.total-blocking-time }} / 100"
